name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        node-version: [15.x]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup npm
        run: npm ci
      - name: Run tests
        env:
          CI: true
          HELLO: ${{ secrets.HELLO }}
        run: npm test
