name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        node-version: [15.x]

    runs-on: ubuntu-latest
    steps:
      - name: Setup npm
        run: npm ci
      - name: Run tests
        env:
          CI: true
          HELLO: ${{ secrets.HELLO }}
        run: npm test
